### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by gab51299** [PinkGoosik/visuality#47]
Crash log below: 

> ---- Minecraft Crash Report ----
> // I let you down. Sorry :(
> 
> Time: 2023-07-11 11:28:50
> Description: Ticking entity
> 
> java.lang.IllegalAccessError: class net.minecraft.class_1309 tried to access private field net.minecraft.class_1297.field_6002 (net.minecraft.class_1309 and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
> 	at net.minecraft.class_1309.handler$bjp002$visuality$tick(class_1309.java:6655)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2499)
> 	at net.minecraft.class_1308.method_5773(class_1308.java:351)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:739)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.class_1309.handler$bjp002$visuality$tick(class_1309.java:6655)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2499)
> 	at net.minecraft.class_1308.method_5773(class_1308.java:351)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:739)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:rabbit (net.minecraft.class_1463)
> 	Entity ID: 1
> 	Entity Name: Rabbit
> 	Entity's Exact location: -10.81, 111.00, 29.09
> 	Entity's Block location: World: (-11,111,29), Section: (at 5,15,13 in -1,6,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> Stacktrace:
> 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 
> -- Affected level --
> Details:
> 	All players: 0 total; []
> 	Chunk stats: 2209
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (0,118,0), Section: (at 0,6,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 11059 game time, 16661 day time
> 	Level name: 1.20 New
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
> 	Level weather: Rain time: 40691 (now: false), thunder time: 145097 (now: false)
> 	Known server brands: fabric
> 	Removed feature flags: 
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by PinkGoosik** [comment]
You're probably trying to run visuality 1.19.4 on 1.20

**Comment by Frempy** [comment]
I have the same issue, running 0.7.0 for 1.20 (curseforge says that version also works for 1.21) minecraft 1.21. Happens as soon as I load into a world or a server.

**Comment by PinkGoosik** [comment]
You might confuse 0.7.0+1.19.4 and 0.7.0+1.20 versions, this issue only occurs when you're trying to run visuality 1.19.4 on 1.20 or 1.20.1, get this https://www.curseforge.com/minecraft/mc-mods/visuality/files/4571997, it does support 1.20.1 but not 1.21(it doesn't exist)
